import './globals.css'
import { Inter } from 'next/font/google'
import NextAuthSessionProvider from '@/providers/sessionProvider'
import { Header } from '@/components/Header'
import { Footer } from '@/components/Footer'
import { ScrollToTop } from '../components/ScrollToTop'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ProjectX',
  description: 'Generated by X',
}

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <Header />
          {children}
          <ScrollToTop />
          <Footer />
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
