import './globals.css'
import { Inter } from 'next/font/google'
import NextAuthSessionProvider from '@/providers/sessionProvider'
import { Theme } from '@radix-ui/themes'
import '@radix-ui/themes/styles.css';
import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import { Hero } from '@/components/Hero'
import { ScrollToTop } from '@/components/ScrollToTop'
import { Sidebar } from '@/components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ProjectX',
  description: 'Generated by X',
}

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <Theme>
            <Header />
            <Sidebar />
            <Hero />
            {children}
            <ScrollToTop />
            <Footer />
          </Theme>
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
