import './globals.css'
import NextAuthSessionProvider from '@/providers/sessionProvider'

export const metadata = {
  title: 'ProjectX',
  description: 'Generated by X',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NextAuthSessionProvider>
          {children}
        </NextAuthSessionProvider>
      </body>
    </html>
  )
}
